[build]
language = "python"

[phases.setup]
nixPkgs = ["python311", "gcc", "portaudio", "libpulseaudio", "alsa-lib"]

[phases.build]
cmds = [ 
  "pip install --upgrade pip",
  "pip install -r requirements.txt"
]

[start]
cmd = "python run.py"
